ARDUINO_DIR = /usr/share/arduino/
TARGET       = TrafficLights

#
MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyACM0

AVRDUDE_ARD_BAUDRATE   = 115200

AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = /etc/avrdude.conf

include /usr/share/arduino/Arduino.mk
