#
# run make in the directory with Makefile
#
ARDUINO_DIR 	= /usr/share/arduino
PROJECT_DIR 	= $(shell pwd)
USER_LIB_PATH  :=  $(PROJECT_DIR)/libraries
BOARD_TAG    	= uno
MONITOR_PORT 	= /dev/ttyACM0

include $(ARDUINO_DIR)/Arduino.mk
